-- En este archivo deben estar tus ejercicios de consultas sql

-- *1.Empleados ordenados alfabéticamente (Z...A):
SELECT NOMBRES
FROM EMPLEADOS
ORDER BY NOMBRES DESC;

-- *2.Empleados de soporte
SELECT E.NOMBRES,
    P.PUESTO,
    L.LOCALIDAD
FROM EMPLEADOS E
    INNER JOIN PUESTOS P ON E.PUESTO_ID = P.ID
    INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
    INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE P.PUESTO = 'Soporte';

-- *3.Nombres que terminan con 'o':
SELECT NOMBRES
FROM EMPLEADOS
WHERE NOMBRES LIKE '%o';

-- *4.Empleados en Carlos Paz:
SELECT E.NOMBRES,
    E.SUELDO,
    L.LOCALIDAD
FROM EMPLEADOS E
    INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
    INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Carlos Paz';

-- *5.Sueldos entre 10000 y 13000:
SELECT E.NOMBRES,
    E.SUELDO,
    L.LOCALIDAD
FROM EMPLEADOS E
    INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
    INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE E.SUELDO BETWEEN 10000 AND 13000;

-- *6.Departamentos con más de 5 empleados:
SELECT D.DENOMINACION AS DEPARTAMENTO,
    COUNT(E.ID) AS CANTIDAD_EMPLEADOS
FROM EMPLEADOS E
    INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
GROUP BY D.DENOMINACION
HAVING COUNT(E.ID) > 5;

-- *7.Empleados en Córdoba con puesto de Analista o Programador:
SELECT E.APELLIDO,
    E.NOMBRES
FROM EMPLEADOS E
    INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
    INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
    INNER JOIN PUESTOS P ON E.PUESTO_ID = P.ID
WHERE L.LOCALIDAD = 'Córdoba'
    AND (
        P.PUESTO = 'Analista'
        OR P.PUESTO = 'Programador'
    );

-- *8.Sueldo medio de todos los empleados:
SELECT AVG(SUELDO) AS SUELDO_MEDIO
FROM EMPLEADOS;

-- *9.Máximo sueldo en el departamento 10: Muestra el máximo sueldo de los empleados del departamento 10.
SELECT MAX(E.SUELDO) AS MAXIMO_SUELDO
FROM EMPLEADOS E
WHERE E.DEPARTAMENTO_ID = 10;

-- *10.Sueldo mínimo en el departamento Soporte:
SELECT MIN(E.SUELDO) AS SUELDO_MINIMO
FROM EMPLEADOS E
    INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
WHERE D.DENOMINACION = 'Soporte';

-- *11.Suma de sueldos por puesto:
SELECT P.PUESTO,
    SUM(E.SUELDO) AS SUMA_SUELDOS
FROM EMPLEADOS E
    INNER JOIN PUESTOS P ON E.PUESTO_ID = P.ID
GROUP BY P.PUESTO;